# Generated by Django 5.2.1 on 2026-01-11 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('calle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle')),
                ('numero_exterior', models.CharField(blank=True, max_length=5, null=True, verbose_name='Número exterior')),
                ('numero_interior', models.CharField(blank=True, max_length=5, null=True, verbose_name='Número interior')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('telefono', models.CharField(blank=True, max_length=10, verbose_name='Teléfono 1')),
                ('extension', models.CharField(blank=True, max_length=3, null=True, verbose_name='Extensión')),
                ('telefono2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono 2')),
                ('movil', models.CharField(blank=True, max_length=10, null=True, verbose_name='Móvil')),
                ('atencion_a', models.CharField(blank=True, max_length=255, verbose_name='Atención a')),
                ('obra', models.CharField(max_length=150, verbose_name='Obra')),
                ('localizacion', models.CharField(blank=True, max_length=150, verbose_name='Localización')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Trabajo realizado')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personal', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('puesto_antiguo', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_empleados/')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_obra', models.CharField(max_length=20, verbose_name='Clave Obra')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Obra')),
                ('atencion_a', models.CharField(blank=True, max_length=255, verbose_name='Atención a')),
                ('localizacion', models.CharField(blank=True, max_length=150, verbose_name='Localización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('otvm', models.PositiveIntegerField(editable=False, verbose_name='O.T.V.M.')),
                ('llegada', models.TimeField(verbose_name='Llegada a las')),
                ('termino', models.TimeField(verbose_name='Término de los trabajos a las')),
                ('solicitante', models.CharField(max_length=100, verbose_name='Solicitó el servicio')),
                ('preguntar_por', models.CharField(max_length=100, verbose_name='Preguntar por')),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('clave_cliente', models.CharField(max_length=100, verbose_name='Clave Cliente')),
                ('localizacion', models.CharField(max_length=150, verbose_name='Localización')),
                ('vobo_cliente_nombre', models.CharField(max_length=100)),
                ('vobo_cliente_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('lab_nombre', models.CharField(max_length=100)),
                ('lab_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('superviso_nombre', models.CharField(max_length=100)),
                ('superviso_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('superviso_fecha', models.DateField()),
                ('capturo_nombre', models.CharField(max_length=100)),
                ('capturo_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('capturo_fecha', models.DateField()),
                ('facturo_nombre', models.CharField(max_length=100)),
                ('facturo_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('factura_numero', models.CharField(blank=True, max_length=20)),
                ('facturo_fecha', models.DateField()),
                ('autorizo_nombre', models.CharField(max_length=100)),
                ('autorizo_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('autorizo_fecha', models.DateField()),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asignados', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='gestion.obra')),
                ('trabajo_realizado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.trabajorealizado')),
            ],
        ),
    ]
