# Generated by Django 5.2.1 on 2026-01-14 05:53

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS gestion_servicio (
                id SERIAL PRIMARY KEY
            );
            CREATE TABLE IF NOT EXISTS gestion_trabajorealizado (
                id INTEGER PRIMARY KEY AUTOINCREMENT
            );
            """
        ),
    ]
