# Generated by Django 5.2.1 on 2025-07-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cliente_calle_cliente_extension_cliente_movil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
    ]
