# Generated by Django 5.2.1 on 2025-07-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cliente_razon_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cfdi',
            field=models.FileField(blank=True, null=True, upload_to='cfdis/'),
        ),
    ]
