# Generated by Django 5.2.1 on 2026-01-14 05:56

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_reparar_tablas'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE gestion_trabajorealizado
            ADD COLUMN nombre VARCHAR(255);
            """
        ),
    ]
