# Generated by Django 5.2.1 on 2025-07-03 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_cliente_cfdi'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_empleados/')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion.empleado')),
            ],
        ),
    ]
