# Generated by Django 5.2.1 on 2025-07-30 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_cliente_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Trabajo realizado')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Número exterior'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_interior',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Número interior'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_obra', models.CharField(max_length=20, verbose_name='Clave Obra')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Obra')),
                ('atencion_a', models.CharField(blank=True, max_length=255, verbose_name='Atención a')),
                ('localizacion', models.CharField(blank=True, max_length=150, verbose_name='Localización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('otvm', models.CharField(max_length=20, verbose_name='O.T.V.M.')),
                ('llegada', models.TimeField(verbose_name='Llegada a las')),
                ('termino', models.TimeField(verbose_name='Término de los trabajos a las')),
                ('solicitante', models.CharField(max_length=100, verbose_name='Solicitó el servicio')),
                ('preguntar_por', models.CharField(max_length=100, verbose_name='Preguntar por')),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('clave_cliente', models.CharField(max_length=100, verbose_name='Clave Cliente')),
                ('localizacion', models.CharField(max_length=150, verbose_name='Localización')),
                ('vobo_cliente_nombre', models.CharField(max_length=100)),
                ('vobo_cliente_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('lab_nombre', models.CharField(max_length=100)),
                ('lab_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('superviso_nombre', models.CharField(max_length=100)),
                ('superviso_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('superviso_fecha', models.DateField()),
                ('capturo_nombre', models.CharField(max_length=100)),
                ('capturo_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('capturo_fecha', models.DateField()),
                ('facturo_nombre', models.CharField(max_length=100)),
                ('facturo_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('factura_numero', models.CharField(blank=True, max_length=20)),
                ('facturo_fecha', models.DateField()),
                ('autorizo_nombre', models.CharField(max_length=100)),
                ('autorizo_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('autorizo_fecha', models.DateField()),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='gestion.obra')),
                ('trabajo_realizado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.trabajorealizado')),
            ],
        ),
    ]
