# Generated by Django 5.2.1 on 2026-01-14 06:00

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE gestion_trabajorealizado
            ADD COLUMN nombre VARCHAR(100) UNIQUE;
            """
        ),
    ]
