# Generated by Django 5.2.1 on 2025-08-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_trabajorealizado_alter_cliente_numero_exterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Postal'),
        ),
    ]
