# Generated by Django 5.2.1 on 2026-01-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_agregar_campos_trabajo'),
        ('gestion', '0004_fix_trabajo_realizado'),
    ]

    operations = [
    ]
