# Generated by Django 5.2.1 on 2026-01-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_merge_20260114_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='superviso_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
