# Generated by Django 5.2.1 on 2025-08-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_cliente_codigo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='firma_autorizo',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='firma_capturo',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='firma_facturo',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='firma_superviso',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
