# Generated by Django 5.2.1 on 2026-01-16 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_servicio_superviso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='trabajo_programado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.trabajorealizado', verbose_name='Trabajo programado'),
        ),
    ]
