# Generated by Django 5.2.1 on 2025-08-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_servicio_firma_autorizo_servicio_firma_capturo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='firma_autorizo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='firma_capturo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='firma_facturo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='firma_superviso',
        ),
    ]
