# Generated by Django 5.2.1 on 2025-08-28 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_servicio_empleado_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Empleado'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
